### ISSUE TITLE
feat: add --config for multi-env

### ISSUE THREAD

**Issue by i5ting** [hiproxy/hiproxy#1]

**Comment by zdying** [comment]
Done. commit [bdc5876](https://github.com/hiproxy/hiproxy/commit/bdc587695e19f097e464470b1defd6ad2d03464d)

**Comment by 592php** [comment]
@i5ting  狼叔 我社区，发测试帖忘记删除被封， 帮我解除下， 账号 https://cnodejs.org/user/592php

**Comment by zdying** [comment]
example: hiproxy start -c ./hosts -c ./hosts1 -r ./rewrite -r ./rewrite1

**Comment by i5ting** [comment]
@592php 已解除
