### ISSUE TITLE
Open the chrome with the open parameter and expect to include the chrome plugin that has already been installed

### ISSUE THREAD

**Issue by huaziHear** [hiproxy/hiproxy#14]
Such as the title, the development process often use the chrome plug-in, how do not have these plug-ins, the experience will be poor

**Comment by zdying** [comment]
启动服务的时候添加了一个选项`--sys-proxy <path>`, 比如：`--sys-proxy 127.0.0.1:1087`，这样**在使用自动代理(使用`--pac-proxy`)**的时候，没有配置在hosts和rewrite中的请求，会经过`127.0.0.1:1087`代理。这样可以使用自己配置的其他代理，登陆Google账户，会自动同步插件和其他配置。

**Comment by huaziHear** [comment]
wow... cool

**Comment by zdying** [comment]
:)
