### ISSUE TITLE
Feature: 支持使用dashboard插件控制rewrite文件启用或禁用

### ISSUE THREAD

**Issue by huaziHear** [hiproxy/hiproxy#20]
通常情况下，workspace中会有多个工程。多个工程势必存在多个rewrite文件，这种情况在开发过程中难免发生一些冲突。所以希望可以在dashboard插件中，在线选择哪些rewrite文件需要启用，哪些需要禁用，方便开发。

**Comment by zdying** [comment]
不错的提议。
