### ISSUE TITLE
BUG：路径的判断有问题

### ISSUE THREAD

**Issue by zhouhailong** [hiproxy/hiproxy#22]
directives.js Line 72 send_file对用户输入的路径判断有问题，需要考虑到各种情况，linux/windows等系统，对于类似需要用户手动输入路径的地方，需要统一处理

**Comment by zhouhailong** [comment]
directives.js ssl_certificate|ssl_certificate_key只支持绝对路径，需要进行适配

**Comment by zdying** [comment]
@zhouhailong 
* `send_file`确实有问题。
*  `ssl_certificate`和`ssl_certificate_key`目前是只支持相对路径（相对于对应的rewrite文件），以后改进

**Comment by zdying** [comment]
fixed
