### ISSUE TITLE
Can't start chrome correctly under Ubuntu

### ISSUE THREAD

**Issue by Jack-Kingdom** [hiproxy/hiproxy#27]
Under different environment, chrome start script is different.  [reference](https://askubuntu.com/questions/234663/what-command-should-i-type-to-run-chrome-from-the-terminal)

![screenshot from 2017-08-15 11-07-31](https://user-images.githubusercontent.com/10584772/29300788-48b6008c-81aa-11e7-8322-56362d4e9aca.png)
![screenshot from 2017-08-15 11-09-01](https://user-images.githubusercontent.com/10584772/29300789-4a5cd834-81aa-11e7-8733-8f9ecc7b8d57.png)

Perhaps we should  add more env check before start.

**Comment by zdying** [comment]
Sorry, 暂时没有考虑到兼容这么多平台。感谢你的反馈，我们会尽快支持Ubuntu。
(如果你愿意帮助我们贡献点代码，也非常欢迎)。

:)

**Comment by zdying** [comment]
@Jack-Kingdom  

依赖的[op-browser](https://www.npmjs.com/package/op-browser)最新版本已经发布，重新安装一下hiproxy可生效。

感谢你帮忙修复！
