### ISSUE TITLE
Feature: 添加init命令

### ISSUE THREAD

**Issue by zdying** [hiproxy/hiproxy#28]
添加init命令，生成一个默认rewrite配置文件到当前目录

**Comment by i5ting** [comment]
ui里没有操作的么？

**Comment by zdying** [comment]
@i5ting dashboard插件里面，暂时么有这个功能，后期可以考虑加上。但是这个命令，可以作为一个辅助，如果不像使用UI, 一个简单的命令也能搞定 :)
