### ISSUE TITLE
[QUESTION] About benchmark and usability

### ISSUE THREAD

**Issue by poppinlp** [hiproxy/hiproxy#31]
Hi, thanks for such a nice tool~
Seems it's a node rewrite for nginx-like service. So how about the bump to performance and easier usability?

**Comment by zdying** [comment]
hi, @poppinlp 
I'm sorry that hiproxy is a proxy tool **for front-end developer**. and it's NOT a  production environment for Nginx alternatives. So, in the production environment certainly need to use Nginx not hiproxy.

:-)

**Comment by poppinlp** [comment]
OK, got it. THX.

**Comment by zdying** [comment]
@poppinlp you are welcome. Thanks for your reply!
