### ISSUE TITLE
hi, start https, but the mobile phone can not coneect, what can i do ?

### ISSUE THREAD

**Issue by 33033624** [hiproxy/hiproxy#38]

**Comment by zdying** [comment]
hi. 需要先配置证书，可以看看文档配置一下
http://hiproxy.org/zh-cn/configuration/ssl_certificate.html

**Comment by 33033624** [comment]
已经解决了，手机和电脑都需要安装证书，命令行执行 -s, 并且手机代理链接的端口号是8008，现在就可以支持https了

**Comment by zdying** [comment]
@33033624 OK，感谢支持
