### ISSUE TITLE
WebSocket 無法運作

### ISSUE THREAD

**Issue by amowu** [hiproxy/hiproxy#39]
Rewrite 是否支持 ws 和 wss 的 protocal 呢？

例如：`ws://hosts.com/...` 導向 `ws://localhost:3000/...`

**Comment by zdying** [comment]
@amowu 

sorry，暂时不支持。

后续版本会考虑支持，但是可能还需要比较长的一段时间。如果有兴趣并且有时间，欢迎PR。

:)

**Comment by jonavila** [comment]
I was very excited until I learned that it doesn't support web sockets. Would love to try to PR, but not sure where to start.

**Comment by zdying** [comment]
@jonavila thanks :)

if you love to submit a PR to support WebSockets. We can talk about how to start later. You can send mail to me. zdying@live.com
