### ISSUE TITLE
Docs: Improve the documentation

### ISSUE THREAD

**Issue by zdying** [hiproxy/hiproxy#4]
Improve the documentation

**Comment by djubreel** [comment]
What exactly is needed on the documentation? I need a guide so I could work on it.

**Comment by zdying** [comment]
@djubreel First of all, thank you for joining. I will write a guide, but it will take some time. When I'm done, I'll tell you. 
:)

**Comment by zdying** [comment]
@djubreel 
i want to add a sub-command `config` for hiproxy. User can use this command to config hiproxy and the config fields will be stored in the user’s home-dir. for example: 

```
hiproxy config set sys-proxy 127.0.0.1:1087
hiproxy config get sys-proxy # 127.0.0.1:1087
hiproxy config list
...
```

Could you do that?
