### ISSUE TITLE
rewrite 文件写多个domain的时候，服务启动后返回 500

### ISSUE THREAD

**Issue by seamoon** [hiproxy/hiproxy#42]
例如：
domain a.domain.com b.domain.com c.domain.com {
    location /static_files/ {
        proxy_pass http://127.0.0.1:81/static_files/;
    }
}

如上的rewrite配置， hiproxy start 起来之后，proxy 返回的对应的请求都是 500.

**Comment by huaziHear** [comment]
抱歉这么晚回复，多个域名配置需要使用逗号分隔

**Comment by zdying** [comment]
@seamoon 最新版hiproxy-conf-parser已经发布。问题已经修复了。

**Comment by seamoon** [comment]
this problem is fixed ， ☆⌒(*＾-゜)v THX!!
