### ISSUE TITLE
兼容 caddy  配置

### ISSUE THREAD

**Issue by zuohuadong** [hiproxy/hiproxy#52]
caddy 配置相对来说要简单很多。
一行配置做反向代理：
```
localhost:80 {
proxy / localhost:3000
}
```

一行，负载均衡+反向代理：
```
localhost:80 {
proxy / localhost:3000 localhost:3001 localhost:3002
}
```

一行配置做跨域：
```
localhost:80 {
proxy / localhost:3000
cors
}
```

一行配置做https:
```
localhost:80 {
proxy / localhost:3000
tls 123@qq.com
}
```

caddy 还可以实现 git 代码自动同步 （通过git 插件）
也可以胜任复杂的 proxy 需求： https://caddyserver.com/docs/proxy

**Comment by zdying** [comment]
@zuohuadong 感谢你的意见，但是我认为，就配置的简洁性而言，caddy的配置没有很明显的优势。暂时没有计划兼容。
