### ISSUE TITLE
Rewrite 如何配置 动态的 Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by impeiran** [hiproxy/hiproxy#68]
往往需要取到request中的origin / host，动态set header，赋值给 Access-Control-Allow-Origin

这一块有什么操作可以做到吗

**Comment by zdying** [comment]
可是使用变量`$http_<header-name>`来获取origin/host等header字段。比如：
```bash
set_header Access-Control-Allow-Origin $http_origin;
```

可以参考文档：<http://hiproxy.org/zh-cn/rewrite/built_in_variable.html#http-name>

**Comment by impeiran** [comment]
@zdying thx
